"""Add emoji votes

Revision ID: 73d5a22f7b1b
Revises: 78dfc6e2e4c4
Create Date: 2024-08-26 16:28:03.291456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d5a22f7b1b'
down_revision = '78dfc6e2e4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji_votes', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji', sa.String(length=20), nullable=True))
        batch_op.drop_column('email_reminders')
        batch_op.drop_column('email_new_articles')
        batch_op.drop_column('email_vote_results')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_vote_results', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_new_articles', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_reminders', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('emoji')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('emoji_votes')

    # ### end Alembic commands ###
