"""add email preferences to User Model

Revision ID: 78dfc6e2e4c4
Revises: 
Create Date: 2024-08-20 15:51:19.261578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dfc6e2e4c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_reminders', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_new_articles', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_vote_results', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_vote_results')
        batch_op.drop_column('email_new_articles')
        batch_op.drop_column('email_reminders')

    # ### end Alembic commands ###
